"""just revision

Revision ID: 2b431e0a915b
Revises: c270756ae635
Create Date: 2022-09-19 19:19:07.582135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b431e0a915b'
down_revision = 'c270756ae635'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('item_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'item_quantity')
    # ### end Alembic commands ###
