"""empty message

Revision ID: 3e34fd3a118e
Revises: 63d8042a4bab
Create Date: 2022-09-19 20:29:34.214897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e34fd3a118e'
down_revision = '63d8042a4bab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workers_user_id_key', 'workers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('workers_user_id_key', 'workers', ['user_id'])
    # ### end Alembic commands ###
