"""just deleted uniqut from login column in Purchase model

Revision ID: 5aa8dec64b92
Revises: fcb9ad3ef4de
Create Date: 2022-09-20 08:25:24.431494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa8dec64b92'
down_revision = 'fcb9ad3ef4de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchases_login_key', 'purchases', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('purchases_login_key', 'purchases', ['login'])
    # ### end Alembic commands ###
