"""added primary key

Revision ID: 63d8042a4bab
Revises: 2b431e0a915b
Create Date: 2022-09-19 19:28:48.088595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d8042a4bab'
down_revision = '2b431e0a915b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
