"""created sequence for workers table

Revision ID: c270756ae635
Revises: db57b657d34b
Create Date: 2022-09-14 19:20:19.349203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c270756ae635'
down_revision = 'db57b657d34b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
