"""making sequence

Revision ID: db57b657d34b
Revises: e14cb30937ef
Create Date: 2022-09-14 15:10:06.108560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db57b657d34b'
down_revision = 'e14cb30937ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
