"""added post column in worker table

Revision ID: e14cb30937ef
Revises: a4b1ea2c64cf
Create Date: 2022-09-12 21:29:29.247641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14cb30937ef'
down_revision = 'a4b1ea2c64cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('workers', sa.Column('post', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'workers', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='unique')
    op.drop_column('workers', 'post')
    op.drop_column('workers', 'user_id')
    # ### end Alembic commands ###
